server:
  port: 8085
  servlet:
    context-path: /community
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: xdcf3233
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1013084647@qq.com #发送邮件的邮箱地址
    password: vtyjlanzumotbehi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1013084647@qq.com # 发送邮件的地址，和上面username一致可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  redis:
    database: 1
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
  task:                  #TaskExecutionProperties
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100

# MybatisProperties
mybatis:
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml
community:
  path:
    domain: http://localhost:8080
    upload: D:/projectdev/community/image



